# Site Configuration
baseURL: https://etherealwake.com/
copyright: "&copy; Jonathan McGee. All Rights Reserved."
defaultContentLanguage: en
languageCode: en-US
title: Ethereal Wake
params:
  author:
    name: Jonathan McGee
    email: jamcgee@etherealwake.com
    url: https://etherealwake.com/
  readingSpeed: 125

# Content Management
frontmatter:
  # Primary date associated with the page.  This is the primary user-visible
  # timestamp, used for filename generation, ordering, and pagination.  It
  # must always have a value.
  date:
    - date
    - publishDate
    - lastmod
    - :git
    - :fileModTime
  # Timestamp for most recent modification.  We give priority to the `lastmod`
  # variable since some pages (like the resume) may be composites of multiple
  # pages and we'll need to update the modification date by hand.  This is
  # primarily used when adding metadata to indices.
  lastmod:
    - lastmod
    - :git
    - :fileModTime
  # Publication date.  Hugo will neither render this page nor include it in
  # default page lists until after this date.  It should not be used for
  # presentation and indexing (use `date` instead).
  publishDate:
    - publishDate
    - date
permalinks:
  article: /:year/:month/:slug/
sectionPagesMenu: menu
taxonomies:
  series: series
  tag: tags

# Rendering
disableKinds:
  - "404"  # Managed by the error collection
enableGitInfo: true
enableRobotsTXT: true
markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
mediaTypes:
  application/atom+xml:
    suffixes:
      - atom
      - xml
  application/rss+xml:
    suffixes:
      - rss
      - xml
outputs:
  home:
    - html
    - atom
    - rss
  section:
    - html
  taxonomy:
    - html
  term:
    - html
    - atom
    - rss
outputFormats:
  atom:
    mediaType: application/atom+xml
  rss:
    mediaType: application/rss+xml
