# Hugo Configuration
baseURL: https://etherealwake.com/
languageCode: en-US
defaultContentLanguage: en
disableKinds: ["404", "RSS"]
enableGitInfo: true
enableRobotsTXT: true

# Site Configuration
title: Ethereal Wake
author:
  name: Jonathan McGee
  email: broken.source@etherealwake.com
copyright: Copyright © 2014-2020 Jonathan McGee

# Theme Configuration
markup:
  goldmark:
    renderer:
      unsafe: true
theme: etherealwake

# Menu Definitions
menu:
  main:
  - name: Home
    url: /
  - identifier: resume
    name: Resume
    url: /resume/
