# Hugo Configuration
baseURL: https://etherealwake.com/
languageCode: en-US
defaultContentLanguage: en
disableKinds:
  - "404"
  - taxonomy
  - term
enableGitInfo: true
enableRobotsTXT: true

# Site Configuration
title: Ethereal Wake
author:
  name: Jonathan McGee
  email: broken.source@etherealwake.com
copyright: Copyright © 2014-2020 Jonathan McGee. All Rights Reserved.

# Theme Configuration
markup:
  goldmark:
    renderer:
      unsafe: true
theme: etherealwake

# Content Management
taxonomies:
  tag: tags
frontmatter:
  # Primary date associated with the page.  This is the primary user-visible
  # timestamp, used for filename generation, ordering, and pagination.  It
  # must always have a value.
  date:
    - date
    - publishDate
    - :filename
    - lastmod
    - :git
    - :fileModTime
  # Timestamp for most recent modification.  We give priority to the `lastmod`
  # variable since some pages (like the resume) may be composites of multiple
  # pages and we'll need to update the modification date by hand.  This is
  # primarily used when adding metadata to indices.
  lastmod:
    - lastmod
    - :git
    - :fileModTime
  # Publication date.  Hugo will neither render this page nor include it in
  # default page lists until after this date.  It should not be used for
  # presentation and indexing (use `date` instead).
  publishDate:
    - publishDate
    - :filename
    - date
permalinks:
  article: /:year/:month/:day:/:slug/

# Content Types
mediaTypes:
  application/atom+xml:
    suffixes: ["atom"]
  application/rss+xml:
    suffixes: ["rss"]
outputFormats:
  ATOM:
    mediaType: application/atom+xml
  RSS:
    mediaType: application/rss+xml
outputs:
  home:
    - html
    - atom
    - rss
  section:
    - html
    - atom
    - rss

# Menu Definitions
menu:
  main:
    - name: Home
      url: /
      weight: 100
    - name: Resume
      url: /resume/
      weight: 200
    - name: Blog
      url: /article/
      weight: 300
    - name: Email
      url: mailto:continuing.search@etherealwake.com
      weight: 400
